[package]
name = "sidewinder-core"
version = "0.1.0"
edition = "2021"

[dependencies]
directories = "6.0.0"

anyhow.workspace = true
tokio-stream.workspace = true
tracing.workspace = true
serde.workspace = true
serde_json.workspace = true
uuid.workspace = true
async-trait = "0.1.88"
